# Generated by Django 4.2.2 on 2023-07-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('date_sortie', models.DateField()),
            ],
        ),
    ]
