# Generated by Django 4.2.2 on 2023-07-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='points_faibles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='points_forts',
            field=models.TextField(blank=True),
        ),
    ]
