# Generated by Django 4.2.2 on 2023-07-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_comment_points_faibles_comment_points_forts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='points_faibles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='points_forts',
            field=models.TextField(null=True),
        ),
    ]
