# Generated by Django 4.2.2 on 2023-07-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0004_alter_comment_points_faibles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
