# Generated by Django 4.2.2 on 2023-07-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0005_alter_film_date_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_sortie',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
