# Generated by Django 4.2.2 on 2023-07-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0006_alter_film_date_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_sortie',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
