# Generated by Django 4.2.2 on 2023-07-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0007_alter_film_date_sortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='ajoute_a_liste',
            field=models.BooleanField(default=False),
        ),
    ]
